import {expect} from 'chai';
import {makeSignal, coalesceSignals} from '../src/lib';

describe('coalesce', () => {
	it('creates a coalesced signal', () => {
		const signal1$ = makeSignal<number>();
		const signal2$ = makeSignal<number>();
		const coalesced$ = coalesceSignals([signal1$, signal2$]);
		let actual = -1;
		coalesced$.subscribe((v) => {
			actual = v;
		});
		expect(actual).to.eq(-1);
		signal1$.emit(1);
		expect(actual).to.eq(1);
		signal2$.emit(2);
		expect(actual).to.eq(2);
	});
	it('checks that the number of subscriptions is consistent', () => {
		const signal1$ = makeSignal<number>();
		const signal2$ = makeSignal<number>();
		const coalesced$ = coalesceSignals([signal1$, signal2$]);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		expect(coalesced$.nOfSubscriptions).to.eq(0);

		const unsubscribe = coalesced$.subscribe(() => undefined);
		expect(signal1$.nOfSubscriptions).to.eq(1);
		expect(signal2$.nOfSubscriptions).to.eq(1);
		expect(coalesced$.nOfSubscriptions).to.eq(1);
		signal1$.emit(10);
		signal2$.emit(10);
		expect(signal1$.nOfSubscriptions).to.eq(1);
		expect(signal2$.nOfSubscriptions).to.eq(1);
		expect(coalesced$.nOfSubscriptions).to.eq(1);
		unsubscribe();
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
	});
	it('tests subscribe once', () => {
		const signal1$ = makeSignal<number>();
		const signal2$ = makeSignal<number>();
		const coalesced$ = coalesceSignals([signal1$, signal2$]);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		let actual = -1;
		coalesced$.subscribeOnce((v) => (actual = v));
		expect(actual).to.eq(-1);
		expect(coalesced$.nOfSubscriptions).to.eq(1);
		expect(signal1$.nOfSubscriptions).to.eq(1);
		expect(signal2$.nOfSubscriptions).to.eq(1);
		signal1$.emit(10);
		expect(actual).to.eq(10);
		signal2$.emit(11);
		expect(actual).to.eq(10);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
	});
	it('unsubscribes from subscribeOnce before emitting', () => {
		const signal1$ = makeSignal<number>();
		const signal2$ = makeSignal<number>();
		const coalesced$ = coalesceSignals([signal1$, signal2$]);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		let actual = -1;
		const unsubscribe = coalesced$.subscribeOnce((v) => (actual = v));
		expect(actual).to.eq(-1);
		expect(coalesced$.nOfSubscriptions).to.eq(1);
		expect(signal1$.nOfSubscriptions).to.eq(1);
		expect(signal2$.nOfSubscriptions).to.eq(1);
		unsubscribe();
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		signal1$.emit(10);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		expect(actual).to.eq(-1);
		signal2$.emit(11);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
		expect(actual).to.eq(-1);
		expect(coalesced$.nOfSubscriptions).to.eq(0);
		expect(signal1$.nOfSubscriptions).to.eq(0);
		expect(signal2$.nOfSubscriptions).to.eq(0);
	});
});
